consumption=read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",skip=66550,col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
consumptionSub$Date=as.Date(consumptionSub$Date,"%d/%m/%Y")
consump1=subset(consumptionSub,Date > "2007-01-31")
consump1=subset(consump1,Date < "2007-02-03")
consump1$Datetime=cbind(paste(consump1$Date,consump1$Time))
consump1$Datetime=strptime(consump1$Datetime,"%Y-%m-%d %H:%M:%S")
consump1$Global_active_power=as.numeric(consump1$Global_active_power)
consump1$Global_reactive_power=as.numeric(consump1$Global_reactive_power)
consump1$Voltage=as.numeric(consump1$Voltage)
consump1$Global_intensity=as.numeric(consump1$Global_intensity)
consump1$Sub_metering_1=as.numeric(consump1$Sub_metering_1)
consump1$Sub_metering_2=as.numeric(consump1$Sub_metering_2)
consump1$Sub_metering_3=as.numeric(consump1$Sub_metering_3)
par(mfrow=c(1,1),mar=c(4,4,2,1))

consump1$Day=weekdays(consump1$Date)
consump1$Day=sub("Thursday","Thu",consump1$Day)
consump1$Day=sub("Friday","Fri",consump1$Day)
with(consump1,plot(Datetime,Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab=""))


dev.copy(png,file="plot2.png")
dev.off()
